{
    'name': "Event Venue Reservation",
    'version': '1.0.0',
    'summary': """To link the event with the venue and assign ticket categories to sections in the designated location.""",
    'description': """To link the event with the venue and assign ticket categories to sections in the designated location.""",
    'author': 'Mustafa Mustafa',
    'company': 'Al-Tanmya IT Solution',
    'website': "https://www.odoo.com",
    'category': 'Event',
    'sequence': -100,
    'depends': ['event','event_sale', 'website_event_sale', 'website_sale','mass_mailing', 'web', 'sale','account'],
    'data': [
        'data/mail_template_data.xml',
        'data/mail_template_data.xml',
        'data/mail_template_data_a5.xml',
        'data/sequence_data.xml',
        'data/mail_sale_order.xml',
        'security/ir.model.access.csv',
        'views/venue_view.xml',
        'views/event_view.xml',
        'views/event_ticket.xml',
        'views/ticket_gift_view.xml',
        'views/season_view.xml',
        'views/season_ticket_view.xml',
        'views/sport_team_view.xml',
        'views/sponsor_view.xml',
        'views/event_templates.xml',
        'views/website_sale_template.xml',
        'views/event_templates_page_registration.xml',
        'views/res_users_view.xml',
        'views/res_config_setting_view.xml',
        'views/season_template.xml',
        'views/portal_templates.xml',
        'views/event_confirmation.xml',
        'report/registration_a4_report.xml',
        'report/registration_a4_report_template.xml',
        'report/registration_a5_report_v1.xml',
        'report/registration_a5_report_template_v1.xml',
    ],

    'assets': {
        'web.assets_frontend': [
            'altanmia_event_venue/static/src/js/form_handler.js',
            'altanmia_event_venue/static/src/js/event_ticket_details.js',
            'altanmia_event_venue/static/src/js/d3.js',
            'altanmia_event_venue/static/src/js/website_event.js',
            'altanmia_event_venue/static/src/js/website_event_attendee_form.js',
            'altanmia_event_venue/static/src/js/event_venue_layout.js',
            'altanmia_event_venue/static/src/js/collapse_tickets.js',
            'altanmia_event_venue/static/src/js/website_cart_timer.js',
            'altanmia_event_venue/static/src/js/over_booking.js',
            'altanmia_event_venue/static/src/css/style.scss',
            "/altanmia_event_venue/static/src/scss/style_form.scss",
            "/altanmia_event_venue/static/src/scss/event_confirmation.scss",
            "/altanmia_event_venue/static/src/css/gift_tickets.css",
            "/altanmia_event_venue/static/src/js/refresh_qr_code.js",
            "altanmia_event_venue/static/src/js/ticket_transfer.js"
        ],
        'web.assets_backend': [
            'altanmia_event_venue/static/src/js/d3.js',
            'altanmia_event_venue/static/src/js/render_venue_map.js',
        ],
        'web.report_assets_common': [
            'altanmia_event_venue/static/src/css/style.scss',
        ],
        'web.report_assets_pdf': [
            'altanmia_event_venue/static/src/css/style.scss',
        ],
    },

    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
}
